@REM g++ -g -std=c++17 -I./include -L./lib -o bin/main.exe src/*.cpp src/glad.c -lglfw3 -lopengl32 -lgdi32
@echo Building GLFW Application...
g++ -g -std=c++17 -I./include -L./lib -o bin/main.exe src/*.cpp -lglfw3 -lopengl32 -lgdi32
@echo Building complete, running Application...
.\bin\main.exe
